# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12509066139f723da170a5d3b6c5d28ab379ac70ee41241cb96e941302c4a61169dc53063e8fa5042046324afee8c5e62e72f34297a674aff5bb71a0af02873d

test:
  secret_key_base: 6400044ac71d881fcc8da3d18eddeb5e05f8c0818fa50edec7b8f0b1a05284be352a3db991da4b7623f2e64ca925460455fb19c34ee8b54af658a988e0d7e47b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
